### ISSUE TITLE
Script strips newline at end of file

### ISSUE THREAD

**Issue by jdloft** [osterman/copyright-header#27]
After I ran the script to add headers to my source, I noticed that all of the files had their newline stripped from the end of the file. This causes many problems related to source control, parsing, and compiling.

**Comment by osterman** [comment]
Hrm... that could be the case. Not sure when I will get around to looking at that. Thanks for reporting the issue.

**Comment by thomasrussellmurphy** [comment]
I could not reproduce this behavior in the current version of `copyright-header` using a file-based license source.

**Comment by osterman** [comment]
Thanks for checking... Will close this for now.

**Comment by osterman** [comment]
Perhaps related: https://github.com/osterman/copyright-header/pull/34
